### ISSUE TITLE
create the output panel util log message

### ISSUE THREAD

**Issue by tjx666** [zardoy/vscode-terminal-code-runner#4]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/41773861/224563424-0aca36f1-c93c-477d-89ba-cfccb05491f1.png">

**Comment by zardoy** [comment]
https://github.com/zardoy/vscode-terminal-code-runner/commit/ae9e3e6f4f45f77f2372321736a021b51c2f6502
